### PR TITLE
✨ Fix invalid sign

### PR DESCRIPTION
**Pull request by damianpumar**

### CODE REVIEW

**Comment by SleepWalker** [comment]
released in https://github.com/SleepWalker/tuya-cloud-api/releases/tag/v1.2.0

**Comment by damianpumar** [comment]
Ok, but be careful, because the PR that you merged has an error here in the arguments. 
https://github.com/SleepWalker/tuya-cloud-api/blob/master/src/httpClient.ts#L120

**Comment by SleepWalker** [comment]
yep, I've noticed it but after the merge. It has passed CI because that is a valid syntax.

I preparing another release where I've refactored that function and there will be no issues with it

**Comment by SleepWalker** [comment]
I've released hotfix version for now

**Pull request closed without merging**
